name:                 mfis-quickcheck-expr
version:              0.1.0.0
visibility:           public
id:                   mfis-quickcheck-expr-0.1.0.0-inplace
key:                  mfis-quickcheck-expr-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           alexn@example.com
author:               Alexandru
synopsis:             Proiect MFIS despre QuickCheck pe un mini-limbaj aritmetic
description:
    Proiect universitar pentru Metode Formale in Ingineria Software.

abi:                  inplace
exposed:              True
exposed-modules:      Eval Expr Parser Pretty Simplify
import-dirs:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\build

library-dirs:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

data-dir:             D:\MFIS_Project\.
hs-libraries:         HSmfis-quickcheck-expr-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\doc\html\mfis-quickcheck-expr\mfis-quickcheck-expr.haddock

haddock-html:
    D:\MFIS_Project\dist-newstyle\build\x86_64-windows\ghc-9.6.7\mfis-quickcheck-expr-0.1.0.0\doc\html\mfis-quickcheck-expr
